# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170328_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.FileField(upload_to=posts.models.post_directory_path),
        ),
    ]
