# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170329_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
