# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170401_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 7, 28, 21, 61000, tzinfo=utc)),
        ),
    ]
