# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0003_auto_20170415_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='visualized',
            field=models.BooleanField(default=True),
        ),
    ]
