# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0004_auto_20170415_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='visualized',
        ),
    ]
